[phases.setup]
nixPkgs = ["nodejs"]
cmds = ["npm install -g pnpm@10.30.1"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start:http"
